/**
 * query all installed fonts
 * window.queryLocalFonts().then(console.log)
 */
export const QUERY_ALL_LOCAL_FONT = 'QUERY_ALL_LOCAL_FONT';
export const LOCAL_FONT_KEY = 'LOCAL_FONT_KEY';
export const FONT_FAMILY_LIST = [
  '等线',
  '等线 Light',
  '方正舒体',
  '方正姚体',
  '仿宋',
  '黑体',
  '华文彩云',
  '华文仿宋',
  '华文琥珀',
  '华文楷体',
  '华文隶书',
  '华文宋体',
  '华文细黑',
  '华文新魏',
  '华文行楷',
  '华文中宋',
  '楷体',
  '隶书',
  '宋体',
  '微软雅黑',
  '微软雅黑 Light',
  '新宋体',
  '幼圆',
  'Arial',
  'Arial Narrow',
  'Cascadia Code',
  'Cascadia Code ExtraLight',
  'Cascadia Code Light',
  'Cascadia Code PL',
  'Cascadia Code PL ExtraLight',
  'Cascadia Code PL Light',
  'Cascadia Code PL SemiBold',
  'Cascadia Code SemiBold',
  'Cascadia Mono',
  'Cascadia Mono ExtraLight',
  'Cascadia Mono Light',
  'Cascadia Mono PL',
  'Cascadia Mono PL ExtraLight',
  'Cascadia Mono PL Light',
  'Cascadia Mono PL SemiBold',
  'Cascadia Mono SemiBold',
  'Microsoft JhengHei',
  'Microsoft JhengHei Light',
  'Microsoft JhengHei UI',
  'Microsoft JhengHei UI Light',
  'Microsoft New Tai Lue',
  'Microsoft PhagsPa',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft Yahei UI',
  'Microsoft YaHei UI Light',
  'Microsoft Yi Baiti',
  'SimSun-ExtB',
  'Times New Roman',
  'Yu Gothic Light',
  'Yu Gothic Medium',
  'Yu Gothic Regular',
  'Yu Gothic UI Light',
  'Yu Gothic UI Regular',
  'Yu Gothic UI Semibold',
];
