/**
 * query all installed fonts
 * window.queryLocalFonts().then(console.log)
 */
export const FONT_FAMILY_LIST = [
  '等线',
  '等线 Light',
  '方正舒体',
  '方正姚体',
  '仿宋',
  '黑体',
  '华文彩云',
  '华文仿宋',
  '华文琥珀',
  '华文楷体',
  '华文隶书',
  '华文宋体',
  '华文细黑',
  '华文新魏',
  '华文行楷',
  '华文中宋',
  '楷体',
  '隶书',
  '宋体',
  '微软雅黑',
  '微软雅黑 Light',
  '新宋体',
  '幼圆',
  'Agency FB',
  'Algerian',
  'Arial',
  'Arial Narrow',
  'Bahnschrift',
  'Bahnschrift Condensed',
  'Bahnschrift Light',
  'Bahnschrift SemiBold',
  'Bahnschrift SemiCondensed',
  'Baskerville Old Face',
  'Bauhaus 93',
  'Bell MT',
  'Berlin Sans FB',
  'Book Antiqua',
  'Bookman Old Style',
  'Bookshelf Symbol 7',
  'Calibri',
  'Calibri Light',
  'Californian FB',
  'Calisto MT',
  'Cambria',
  'Cambria Math',
  'Candara',
  'Candara Light',
  'Cascadia Code',
  'Cascadia Code',
  'Cascadia Code ExtraLight',
  'Cascadia Code ExtraLight',
  'Cascadia Code Light',
  'Cascadia Code Light',
  'Cascadia Code PL',
  'Cascadia Code PL ExtraLight',
  'Cascadia Code PL Light',
  'Cascadia Code PL SemiBold',
  'Cascadia Code SemiBold',
  'Cascadia Code SemiBold',
  'Cascadia Mono',
  'Cascadia Mono',
  'Cascadia Mono ExtraLight',
  'Cascadia Mono ExtraLight',
  'Cascadia Mono Light',
  'Cascadia Mono Light',
  'Cascadia Mono PL',
  'Cascadia Mono PL ExtraLight',
  'Cascadia Mono PL Light',
  'Cascadia Mono PL SemiBold',
  'Cascadia Mono SemiBold',
  'Cascadia Mono SemiBold',
  'Castellar',
  'Centaur',
  'Century',
  'Century Gothic',
  'Century Schoolbook',
  'Colonna MT',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Cooper Black',
  'Copperplate Gothic Light',
  'Corbel',
  'Corbel Light',
  'Courier New',
  'Dubai Light',
  'Dubai Medium',
  'Dubai Regular',
  'Ebrima',
  'Elephant',
  'Engravers MT',
  'Felix Titling',
  'Footlight MT Light',
  'Franklin Gothic Book',
  'Franklin Gothic Heavy',
  'Franklin Gothic Medium',
  'Leelawadee UI',
  'Lucida Bright',
  'Lucida Bright Demibold',
  'Lucida Console',
  'Lucida Fax',
  'Lucida Sans',
  'Lucida Sans Typewriter',
  'Lucida Sans Unicode',
  'Maiandra GD',
  'Malgun Gothic',
  'Microsoft JhengHei',
  'Microsoft JhengHei Light',
  'Microsoft JhengHei UI',
  'Microsoft JhengHei UI Light',
  'Microsoft New Tai Lue',
  'Microsoft PhagsPa',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft Yahei UI',
  'Microsoft YaHei UI Light',
  'Microsoft Yi Baiti',
  'Modern No. 20',
  'Mongolian Baiti',
  'MS Gothic',
  'MS PGothic',
  'MS Reference Sans Serif',
  'MS UI Gothic',
  'Rockwell',
  'Rockwell Condensed',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Segoe UI Black',
  'Segoe UI Emoji',
  'Segoe UI Historic',
  'Segoe UI Light',
  'Segoe UI Semibold',
  'Segoe UI Symbol',
  'Segoe UI Variable Display',
  'Segoe UI Variable Display Light',
  'Segoe UI Variable Display Semibold',
  'Segoe UI Variable Small',
  'Segoe UI Variable Small Light',
  'Segoe UI Variable Small Semibold',
  'Segoe UI Variable Text',
  'Segoe UI Variable Text Light',
  'Segoe UI Variable Text Semibold',
  'SimSun-ExtB',
  'Sitka Banner',
  'Sitka Banner Semibold',
  'Sitka Display',
  'Sitka Display Semibold',
  'Sitka Heading',
  'Sitka Heading Semibold',
  'Sitka Small',
  'Sitka Small Semibold',
  'Sitka Subheading',
  'Sitka Subheading Semibold',
  'Sitka Text',
  'Sitka Text Semibold',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
  'Wide Latin',
  'Wingdings 2',
  'Wingdings 3',
  'Yu Gothic Light',
  'Yu Gothic Medium',
  'Yu Gothic Regular',
  'Yu Gothic UI Light',
  'Yu Gothic UI Regular',
  'Yu Gothic UI Semibold',
];
