export declare const theme: {
    primaryColor: string;
    buttonActiveColor: string;
    selectionColor: string;
    backgroundColor: string;
    white: string;
    black: string;
    gridStrokeColor: string;
    triangleFillColor: string;
    contentColor: string;
    borderColor: string;
    activeBorderColor: string;
    disabledColor: string;
    smallFont: string;
    font: string;
    largeFont: string;
    padding: string;
    lineHeight: string;
    mediumPadding: string;
    borderRadius: string;
    tinyPadding: string;
};
