export var TokenType;
(function (TokenType) {
    TokenType[TokenType["EQUAL"] = 0] = "EQUAL";
    TokenType[TokenType["NOT_EQUAL"] = 1] = "NOT_EQUAL";
    TokenType[TokenType["PLUS"] = 2] = "PLUS";
    TokenType[TokenType["MINUS"] = 3] = "MINUS";
    TokenType[TokenType["STAR"] = 4] = "STAR";
    TokenType[TokenType["SLASH"] = 5] = "SLASH";
    TokenType[TokenType["EXPONENT"] = 6] = "EXPONENT";
    TokenType[TokenType["GREATER"] = 7] = "GREATER";
    TokenType[TokenType["GREATER_EQUAL"] = 8] = "GREATER_EQUAL";
    TokenType[TokenType["CONCATENATE"] = 9] = "CONCATENATE";
    TokenType[TokenType["COLON"] = 10] = "COLON";
    TokenType[TokenType["COMMA"] = 11] = "COMMA";
    TokenType[TokenType["EMPTY_CHAR"] = 12] = "EMPTY_CHAR";
    TokenType[TokenType["PERCENT"] = 13] = "PERCENT";
    TokenType[TokenType["LESS"] = 14] = "LESS";
    TokenType[TokenType["LESS_EQUAL"] = 15] = "LESS_EQUAL";
    TokenType[TokenType["IDENTIFIER"] = 16] = "IDENTIFIER";
    TokenType[TokenType["STRING"] = 17] = "STRING";
    TokenType[TokenType["NUMBER"] = 18] = "NUMBER";
    TokenType[TokenType["TRUE"] = 19] = "TRUE";
    TokenType[TokenType["FALSE"] = 20] = "FALSE";
    TokenType[TokenType["LEFT_BRACKET"] = 21] = "LEFT_BRACKET";
    TokenType[TokenType["RIGHT_BRACKET"] = 22] = "RIGHT_BRACKET";
    TokenType[TokenType["lEFT_BRACE"] = 23] = "lEFT_BRACE";
    TokenType[TokenType["RIGHT_BRACE"] = 24] = "RIGHT_BRACE";
    TokenType[TokenType["SEMICOLON"] = 25] = "SEMICOLON";
    TokenType[TokenType["EXCLAMATION"] = 26] = "EXCLAMATION";
    TokenType[TokenType["EOF"] = 27] = "EOF";
})(TokenType || (TokenType = {}));
//# sourceMappingURL=parser.js.map