const {
  VITE_DEFAULT_EXCEL_ID,
  BASE_URL,
  VITE_BACKEND_URL,
  VITE_WEBSOCKET_URL,
} = import.meta.env;

export {
  VITE_DEFAULT_EXCEL_ID,
  BASE_URL,
  VITE_BACKEND_URL,
  VITE_WEBSOCKET_URL,
};
