const { VITE_DEFAULT_EXCEL_ID, VITE_BACKEND_URL, VITE_WEBSOCKET_URL } =
  import.meta.env;

console.log(
  'VITE_DEFAULT_EXCEL_ID, VITE_BACKEND_URL, VITE_WEBSOCKET_UR:',
  VITE_DEFAULT_EXCEL_ID,
  VITE_BACKEND_URL,
  VITE_WEBSOCKET_URL,
);

export { VITE_DEFAULT_EXCEL_ID, VITE_BACKEND_URL, VITE_WEBSOCKET_URL };
