import type { MathFormulaType } from '../../types';
export declare const ABS: (...list: any[]) => number;
export declare const ACOS: (...list: any[]) => number;
export declare const ACOSH: (...list: any[]) => number;
export declare const ACOT: (...list: any[]) => number;
export declare const ACOTH: (...list: any[]) => number;
export declare const ASIN: (...list: any[]) => number;
export declare const ASINH: (...list: any[]) => number;
export declare const ATAN: (...list: any[]) => number;
export declare const ATAN2: (...list: any[]) => number;
export declare const ATANH: (...list: any[]) => number;
export declare const COS: (...list: any[]) => number;
export declare const COT: (...list: any[]) => number;
export declare const CSC: (...list: any[]) => number;
export declare const DECIMAL: (...list: any[]) => number;
export declare const DEGREES: (...list: any[]) => number;
export declare const EXP: (...list: any[]) => number;
export declare const INT: (...list: any[]) => number;
export declare const LN10: (...list: any[]) => number;
export declare const LN2: (...list: any[]) => number;
export declare const LOG10E: (...list: any[]) => number;
export declare const LOG2E: (...list: any[]) => number;
export declare const LOG: (...list: any[]) => number;
export declare const LOG10: (...list: any[]) => number;
export declare const PI: (...list: any[]) => number;
export declare const E: (...list: any[]) => number;
export declare const SIN: (...list: any[]) => number;
export declare const SUM: (...rest: any[]) => number;
declare const formulas: MathFormulaType;
export default formulas;
